### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [biokoda/actordb#15]
hi, when i try actordb, i found some difficulties, could you please provide some help?
```
1, i follow the document to run, the default username and password was in etc/init.example.sql, why not tell user firiendly?
2, i use navicat to connect to 127.0.0.1:33307, but can not list any table, just connected, nothing displayed, i also use intellij idea to connect actordb, but could not connected(intellij idea use java mysql client).
so is there a offical gui admin tool?
3, as problem 2, i'm not sure, can mysql client really work? if you provide some mysql client sample, it will be much better, php, java, ruby, python, golang, erlang etc.
```

there is no comminity of actordb, if the problems above can be solved, i think that will be much better.
thank you for your great hard work!

**Comment by SergejJurecko** [comment]
1. Thanks for the report. You are right we should mention that. We will improve documentation.
2. ActorDB requires "actor mytype(..)" statements before other SQL statements. These gui tools for MySQL can't really be used because of it.
3. You can connect using a MySQL driver just fine and run queries. You just have to use "actor .." statements.

**Comment by ziyouchutuwenwu** [comment]
thank you!
i'll try to use any mysql driver to test, still expect a gui admin tool :)
