### ISSUE TITLE
Understanding nodes, clusters, replication & sharding in ActorDB

### ISSUE THREAD

**Issue by kulshekhar** [biokoda/actordb#21]
I've been reading the docs and the other issues here and here's my understanding so far:

- A cluster is made up of nodes and every node in a cluster is identical. More nodes would improve reliability and throughput with respect to data in that particular cluster.
- Multiple clusters can be used to increase the storage space horizontally.

Another way to express my understanding is:

- If I need to improve reliability or throughput, I would add more nodes clusters.
- If I need to increase the storage space over multiple machines, I would add more clusters.

Is this understanding accurate or have I misunderstood something?

**Comment by SergejJurecko** [comment]
Mostly correct. More nodes in a cluster do not increase write throughput, but they do increase read throughput. Writes get replicated to all nodes within a cluster. You are actually decreasing write throughput with every additional node. More nodes in a cluster increases reliability. 

More clusters increase throughput and storage capacity.

**Comment by kulshekhar** [comment]
Thanks for the clarification. 

Some related follow up questions:

- I imagine that actors of the same type will be spread over multiple clusters as their number grows.
- A complete backup would involve backing up the `/path/to/source/lmdb` for any node in each cluster for all clusters.

Is this right?

Is there a way to do realtime streaming backups?

**Comment by SergejJurecko** [comment]
> I imagine that actors of the same type will be spread over multiple clusters as their number grows.

Yes

> A complete backup would involve backing up the /path/to/source/lmdb for any node in each cluster for all clusters.

Yes. Generally you could get away with just backing up one of the nodes in the cluster, but backing up every node is safer because so you don't loose writes that may not have been fully replicated to the node you are backing up.

Real time streaming backups are not available at the moment yet. I think it's on the roadmap for LMDB, which we can piggy back on. It would be possible to do it without waiting for them, but it would not be as efficient.

We are considering a geo replication mode, which would basically be a backup option. Right now the plan is: An active cluster in one datacenter, replicates to another (or more) passive cluster in another datacenter. Then there is an API call that switches which of the two clusters is the active one. This idea may change however. It's our thinking at the moment.

**Comment by kulshekhar** [comment]
This clarifies the idea I have of ActorDB in my head. It's great to see that streaming backups and geo replication are being considered and I agree with your view on waiting for LMDB to implement it. 

I'll continue digging into ActorDB further and will probably be asking some more questions :)
