### ISSUE TITLE
2pc deadlock

### ISSUE THREAD

**Issue by glycerine** [biokoda/actordb#34]
It appears that distributed actor transactions use a transaction manager and two-phase commit protocol. This is a very nice feature of actordb.

However it is well known that 2-phase commit can suffer from deadlock.

Does actordb provide deadlock detection and recovery?

**Comment by SergejJurecko** [comment]
I'm afraid this is an oversight on our part because we consider multiactor transactions to be bad practice.  We will address this in the next version.

**Comment by glycerine** [comment]
> consider multiactor transactions to be bad practice

Yes, agreed, and always a performance concern. But sometimes they are just unavoidable.

> We will address this in the next version

 I do hope you retain distributed transactions.  

A little additional guidance/warning in docs might suffice for now, if the next version will be a while.

**Comment by SergejJurecko** [comment]
Fixed in master. The algorithm is quite ruthless as it will kill and restart transactions according to sort order of transaction manager id. It guarantees progress but can cause a lot of extra work. But as I said, if anyone is using a lot of multiactor transactions you are using this DB wrong.

Thank you very much for the report.

**Comment by glycerine** [comment]
Excellent. Thank you, @SergejJurecko.
